"""Variable-cell nudged elastic band helpers built on ASE."""

from .version import __version__
from .core import (
    VCNEB,
    VCNEBState,
    apply_chain_state,
    infer_atom_mapping,
    interpolate_vcneb,
    path_geometry_diagnostics,
    read_chain_trajectory,
    run_vcneb,
    validate_atom_mapping,
    validate_candidate_cell_step,
    validate_path_geometry,
)
from .calculator import (
    CalculatorCapabilities,
    CalculatorCapabilityError,
    classify_calculator_failure,
    inspect_calculator,
    validate_calculator,
    validate_image_calculators,
)
from .modes import (
    Mode,
    build_direction_basis,
    build_mode_basis,
    direction_basis_conflicts,
    mode_guided_path,
    project_path_onto_modes,
)
from .executor import ImageEvaluation, ThreadedCalculatorExecutor
from .qe import (
    attach_qe_calculators,
    load_approved_qe_pseudopotential_manifest,
    make_ase_espresso_factory,
    static_qe_input_data,
    validate_qe_pseudopotentials,
)
from .backends import (
    BackendSpec,
    attach_image_calculators,
    backend_capability_matrix,
    backend_specs,
    get_backend_spec,
    make_ase_calculator_factory,
    make_ase_abinit_factory,
    make_ase_cp2k_factory,
    make_ase_lammps_factory,
)
from .phonons import (
    GammaModes,
    PhonopyGammaEigenpairs,
    anchored_gamma_axis_weights,
    diagonalize_gamma_modes,
    force_constants_to_eV_per_A2,
    gamma_modes_from_phonopy_eigenpairs,
    load_gamma_force_constants,
    load_phonopy_gamma_eigenpairs,
    phonopy_gamma_eigenpairs,
    project_displacements_onto_gamma_modes,
    save_phonopy_gamma_eigenpairs,
    tangent_mode_overlaps,
)
from .analysis import dominant_mode_indices, mode_contribution_fractions, path_reaction_coordinate
from .mode_surface import (
    ModePlane, ModeEnergyGrid, FrozenModeSurface, ConditionalBranchOutcome, ConditionalModePoint,
    ConditionalModeSurface, ConditionalSurfaceContinuityAudit,
    audit_conditional_surface_continuity, OrthogonalCurvatureAudit, audit_orthogonal_curvature,
    PairedEnergyCurvatureAudit, audit_paired_energy_curvature,
    DirectionalCurvatureConsistencyAudit, audit_directional_curvature_consistency,
    CurvatureEnergyResolutionScreen, screen_curvature_energy_resolution,
    orthogonal_branch_seeds,
    sample_frozen_mode_surface,
    sample_conditional_mode_surface, relax_orthogonal_at_q,
)
from .reference_cell import ReferenceCellCoordinates
from .mode_evaluator import CalculatorModeEvaluator
from .mode_subspace import (
    StrictModeSubspace, strict_mode_subspace_for_vcneb,
    EndpointCompletedModeSubspace, endpoint_completed_mode_subspace_for_vcneb,
    make_vcneb_subspace_artifact, load_vcneb_subspace_artifact,
)
from .provenance import (
    compare_endpoint_records,
    endpoint_structure_record,
    validate_static_endpoint_identity,
)
from .config import RunConfig, prepare_run
from .optimizer_registry import (
    OptimizerSpec,
    get_optimizer_spec,
    optimizer_capability_matrix,
    optimizer_specs,
)

__all__ = [
    "VCNEB",
    "__version__",
    "VCNEBState",
    "apply_chain_state",
    "infer_atom_mapping",
    "interpolate_vcneb",
    "path_geometry_diagnostics",
    "read_chain_trajectory",
    "run_vcneb",
    "validate_atom_mapping",
    "validate_candidate_cell_step",
    "validate_path_geometry",
    "CalculatorCapabilities",
    "CalculatorCapabilityError",
    "classify_calculator_failure",
    "inspect_calculator",
    "validate_calculator",
    "validate_image_calculators",
    "Mode",
    "build_mode_basis",
    "build_direction_basis",
    "direction_basis_conflicts",
    "mode_guided_path",
    "project_path_onto_modes",
    "ImageEvaluation",
    "ThreadedCalculatorExecutor",
    "attach_qe_calculators",
    "make_ase_espresso_factory",
    "static_qe_input_data",
    "load_approved_qe_pseudopotential_manifest",
    "validate_qe_pseudopotentials",
    "BackendSpec",
    "attach_image_calculators",
    "backend_capability_matrix",
    "backend_specs",
    "get_backend_spec",
    "make_ase_calculator_factory",
    "make_ase_abinit_factory",
    "make_ase_cp2k_factory",
    "make_ase_lammps_factory",
    "GammaModes",
    "PhonopyGammaEigenpairs",
    "anchored_gamma_axis_weights",
    "diagonalize_gamma_modes",
    "force_constants_to_eV_per_A2",
    "gamma_modes_from_phonopy_eigenpairs",
    "load_gamma_force_constants",
    "load_phonopy_gamma_eigenpairs",
    "phonopy_gamma_eigenpairs",
    "project_displacements_onto_gamma_modes",
    "save_phonopy_gamma_eigenpairs",
    "tangent_mode_overlaps",
    "dominant_mode_indices",
    "mode_contribution_fractions",
    "path_reaction_coordinate",
    "ModePlane",
    "ModeEnergyGrid",
    "FrozenModeSurface",
    "ConditionalBranchOutcome",
    "ConditionalModePoint",
    "ConditionalModeSurface",
    "ConditionalSurfaceContinuityAudit",
    "audit_conditional_surface_continuity",
    "OrthogonalCurvatureAudit",
    "audit_orthogonal_curvature",
    "PairedEnergyCurvatureAudit",
    "audit_paired_energy_curvature",
    "DirectionalCurvatureConsistencyAudit",
    "audit_directional_curvature_consistency",
    "CurvatureEnergyResolutionScreen",
    "screen_curvature_energy_resolution",
    "sample_frozen_mode_surface",
    "sample_conditional_mode_surface",
    "relax_orthogonal_at_q",
    "orthogonal_branch_seeds",
    "ReferenceCellCoordinates",
    "CalculatorModeEvaluator",
    "StrictModeSubspace",
    "strict_mode_subspace_for_vcneb",
    "EndpointCompletedModeSubspace",
    "endpoint_completed_mode_subspace_for_vcneb",
    "make_vcneb_subspace_artifact",
    "load_vcneb_subspace_artifact",
    "endpoint_structure_record",
    "compare_endpoint_records",
    "validate_static_endpoint_identity",
    "RunConfig",
    "prepare_run",
    "OptimizerSpec",
    "get_optimizer_spec",
    "optimizer_capability_matrix",
    "optimizer_specs",
]
