"""Variable-cell nudged elastic band helpers built on ASE."""

from .version import __version__
from .core import (
    VCNEB,
    VCNEBState,
    apply_chain_state,
    infer_atom_mapping,
    interpolate_vcneb,
    path_geometry_diagnostics,
    read_chain_trajectory,
    run_vcneb,
    validate_atom_mapping,
    validate_path_geometry,
)
from .calculator import (
    CalculatorCapabilities,
    CalculatorCapabilityError,
    classify_calculator_failure,
    inspect_calculator,
    validate_calculator,
    validate_image_calculators,
)
from .modes import (
    Mode,
    build_direction_basis,
    build_mode_basis,
    direction_basis_conflicts,
    mode_guided_path,
    project_path_onto_modes,
)
from .executor import ImageEvaluation, ThreadedCalculatorExecutor
from .qe import (
    attach_qe_calculators,
    load_approved_qe_pseudopotential_manifest,
    make_ase_espresso_factory,
    static_qe_input_data,
    validate_qe_pseudopotentials,
)
from .backends import (
    BackendSpec,
    attach_image_calculators,
    backend_capability_matrix,
    backend_specs,
    get_backend_spec,
    make_ase_calculator_factory,
    make_ase_abinit_factory,
    make_ase_cp2k_factory,
    make_ase_lammps_factory,
)
from .phonons import (
    GammaModes,
    PhonopyGammaEigenpairs,
    diagonalize_gamma_modes,
    force_constants_to_eV_per_A2,
    gamma_modes_from_phonopy_eigenpairs,
    load_gamma_force_constants,
    load_phonopy_gamma_eigenpairs,
    phonopy_gamma_eigenpairs,
    project_displacements_onto_gamma_modes,
    save_phonopy_gamma_eigenpairs,
    tangent_mode_overlaps,
)
from .analysis import dominant_mode_indices, mode_contribution_fractions, path_reaction_coordinate
from .provenance import compare_endpoint_records, endpoint_structure_record
from .config import RunConfig, prepare_run
from .optimizer_registry import (
    OptimizerSpec,
    get_optimizer_spec,
    optimizer_capability_matrix,
    optimizer_specs,
)

__all__ = [
    "VCNEB",
    "__version__",
    "VCNEBState",
    "apply_chain_state",
    "infer_atom_mapping",
    "interpolate_vcneb",
    "path_geometry_diagnostics",
    "read_chain_trajectory",
    "run_vcneb",
    "validate_atom_mapping",
    "validate_path_geometry",
    "CalculatorCapabilities",
    "CalculatorCapabilityError",
    "classify_calculator_failure",
    "inspect_calculator",
    "validate_calculator",
    "validate_image_calculators",
    "Mode",
    "build_mode_basis",
    "build_direction_basis",
    "direction_basis_conflicts",
    "mode_guided_path",
    "project_path_onto_modes",
    "ImageEvaluation",
    "ThreadedCalculatorExecutor",
    "attach_qe_calculators",
    "make_ase_espresso_factory",
    "static_qe_input_data",
    "load_approved_qe_pseudopotential_manifest",
    "validate_qe_pseudopotentials",
    "BackendSpec",
    "attach_image_calculators",
    "backend_capability_matrix",
    "backend_specs",
    "get_backend_spec",
    "make_ase_calculator_factory",
    "make_ase_abinit_factory",
    "make_ase_cp2k_factory",
    "make_ase_lammps_factory",
    "GammaModes",
    "PhonopyGammaEigenpairs",
    "diagonalize_gamma_modes",
    "force_constants_to_eV_per_A2",
    "gamma_modes_from_phonopy_eigenpairs",
    "load_gamma_force_constants",
    "load_phonopy_gamma_eigenpairs",
    "phonopy_gamma_eigenpairs",
    "project_displacements_onto_gamma_modes",
    "save_phonopy_gamma_eigenpairs",
    "tangent_mode_overlaps",
    "dominant_mode_indices",
    "mode_contribution_fractions",
    "path_reaction_coordinate",
    "endpoint_structure_record",
    "compare_endpoint_records",
    "RunConfig",
    "prepare_run",
    "OptimizerSpec",
    "get_optimizer_spec",
    "optimizer_capability_matrix",
    "optimizer_specs",
]
